stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\resume.csv  .\data\processed  .\make_data_logfile.log  .\data\nltk\  .\params.yaml
    # deps:
    # - .\src\data\make_dataset.py  
    # - .\data\raw\resume.csv

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\ .\params.yaml .\models .\train_logfile.log
    deps:
      - .\src\data\make_dataset.py


  evaluate_model:
    cmd: python .\src\evaluate\evaluate.py  .\data\processed\  .\models\  .\params.yaml  .\evaluate_log.log
    deps:
      - .\src\models\train_model.py
 
  app:
    cmd: streamlit run main.py .\src\evaluate\evaluate_log.log  .\data\nltk\  .\models\  .\data\processed\train_df.csv
    # deps:
    #   - .\src\evaluate\evaluate.py