stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw\resume.csv  .\data\processed  .\make_data_logfile.log
    # deps:
    # - .\src\data\make_dataset.py  
    # - .\data\raw\resume.csv